### ISSUE TITLE
iroiro

### ISSUE THREAD

**Issue by izszzz** [izszzz/tunescore#226]
# Task
- [x] Music Model add isrc column
- [x] fix typo visibilioty to visibillity
- [x] fix `()=>onClick && onClick()` to `onClick?.()`
- [x] https://github.com/izszzz/tunescore/issues/208
- [x] fix dark mode 
- [x] add setting dialog (ambient mode / theme)
- [x] remove ResourceIcon

# Fix DarkMode
```
Warning: Prop `className` did not match.
```
- `https://github.com/mui/material-ui/issues/18018`
- https://www.geeksforgeeks.org/how-to-use-material-ui-with-next-js/
- https://github.com/vercel/next.js/tree/deprecated-main/examples/with-emotion-vanilla
- https://github.com/mui/material-ui/tree/master/examples/material-next-ts
- `https://github.com/juliencrn/usehooks-ts/issues/84` これっぽい
- https://brianlovin.com/writing/adding-dark-mode-with-next-js
